### ISSUE TITLE
Docker Volume Problem

### ISSUE THREAD

**Issue by sopaoglu** [a-mma/AquilaDB#45]
I am using following YAML to run AquilaDb
```
version: '3'
services:
  aquiladb:
    image: ammaorg/aquiladb
    ports:
      - "50051:50051"
    volumes:
      - /home/asd/db-data:/data
    restart: always
volumes:
  db-data:
```
But when I remove the container, I start again it but all the indexes are lost. Probably It happens to because all files under default_docsdb are removed and new ones are added.
